services:
  frontend:
    build:
      context: ../kasun.com-blog
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../kasun.com-blog:/app
      - /app/node_modules
    env_file:
      - ../kasun.com-blog/.env
    environment:
      NEXT_PUBLIC_STRAPI_API_URL: http://localhost:1337
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1337"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      NODE_ENV: development
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - strapi_pg_data_seeka_blog_system:/var/lib/postgresql/data

volumes:
  strapi_pg_data_seeka_blog_system:
